DROP TABLE PRODUCTO
/*sql-break*/
DROP TABLE METRICA
/*sql-break*/
DROP TABLE CATEGORIA
/*sql-break*/
DROP TABLE FACTURAUNIDAD
/*sql-break*/
DROP TABLE FACTURA
/*sql-break*/
DROP TABLE VENTAUNIDAD
/*sql-break*/
DROP TABLE VENTA
/*sql-break*/
CREATE TABLE METRICA(
   METRICA_ID SMALLINT PRIMARY KEY NOT NULL,
   METRICA_NOMBRE VARCHAR(32) NOT NULL,
   METRICA_SIMBOLO VARCHAR(6) NOT NULL
)
/*sql-break*/
CREATE TABLE CATEGORIA (
    CATEGORIA_ID CHAR(16) FOR BIT DATA NOT NULL,
    CATEGORIA_NOMBRE VARCHAR(64) NOT NULL,
    CATEGORIA_IMPUESTOPRINCIPAL BIGINT DEFAULT 0,
    CATEGORIA_IMPUESTOSECUNDARIO BIGINT DEFAULT 0,
    CATEGORIA_PORCENTAJEGANANCIA BIGINT DEFAULT 0,
    PRIMARY KEY (CATEGORIA_ID),
    UNIQUE(CATEGORIA_NOMBRE)
)
/*sql-break*/
CREATE TABLE PRODUCTO(
    PRODUCTO_ID CHAR(16) FOR BIT DATA NOT NULL,
    PRODUCTO_CODIGO VARCHAR(16) NOT NULL,
    PRODUCTO_DESCRIPCION VARCHAR(128) DEFAULT '',
    PRODUCTO_PRECIOVENTAACTUAL BIGINT DEFAULT 0,
    PRODUCTO_INCLUIRENBOLETA BOOLEAN DEFAULT TRUE,
    PRODUCTO_PRECIOVENTAFIJO BOOLEAN DEFAULT TRUE,
    PRODUCTO_STOCKCOMPRADO BIGINT DEFAULT 0,
    PRODUCTO_STOCKVENDIDO BIGINT DEFAULT 0,
    PRODUCTO_METRICA_ID SMALLINT REFERENCES METRICA(METRICA_ID),
    PRODUCTO_CATEGORIA_ID CHAR(16) FOR BIT DATA REFERENCES CATEGORIA(CATEGORIA_ID),
    PRIMARY KEY (PRODUCTO_ID),
    UNIQUE(PRODUCTO_CODIGO)
)
/*sql-break*/
CREATE TABLE FACTURA(
    FACTURA_ID CHAR(16) FOR BIT DATA NOT NULL,
    FACTURA_CODIGO VARCHAR(32),
    FACTURA_FECHA DATE NOT NULL,
    PRIMARY KEY (FACTURA_ID)
)
/*sql-break*/
CREATE TABLE FACTURAUNIDAD(
    FACTURAUNIDAD_ID CHAR(16) FOR BIT DATA NOT NULL,
    FACTURAUNIDAD_IDPRODUCTO CHAR(16) FOR BIT DATA REFERENCES PRODUCTO(PRODUCTO_ID),
    FACTURAUNIDAD_PRECIONETOCOMPRA BIGINT DEFAULT 0,
    FACTURAUNIDAD_CANTIDAD BIGINT DEFAULT 0,
    FACTURAUNIDAD_FACTURA_ID CHAR(16) FOR BIT DATA REFERENCES FACTURA(FACTURA_ID) ON DELETE CASCADE,
    PRIMARY KEY (FACTURAUNIDAD_ID)
)
/*sql-break*/
CREATE TABLE VENTA(
    VENTA_ID CHAR(16) FOR BIT DATA NOT NULL,
    VENTA_CODIGO VARCHAR(32),
    VENTA_FECHA DATE NOT NULL,
    PRIMARY KEY (VENTA_ID)
)
/*sql-break*/
CREATE TABLE VENTAUNIDAD(
    VENTAUNIDAD_ID CHAR(16) FOR BIT DATA NOT NULL,
    VENTAUNIDAD_IDPRODUCTO CHAR(16) FOR BIT DATA REFERENCES PRODUCTO(PRODUCTO_ID),
    VENTAUNIDAD_PRECIOVENTA BIGINT DEFAULT 0,
    VENTAUNIDAD_CANTIDAD BIGINT DEFAULT 0,
    VENTAUNIDAD_VENTA_ID CHAR(16) FOR BIT DATA REFERENCES VENTA(VENTA_ID) ON DELETE CASCADE,
    PRIMARY KEY (VENTAUNIDAD_ID)
)